// ═══════════════════════════════════════════════════════
// DIRECTORIO JUDICIAL NACIONAL — Datos reales
// Links a portales judiciales, consulta de expedientes,
// colegios de abogados y MEV de cada provincia.
// ═══════════════════════════════════════════════════════

export const provincialDirectory = [
    {
        province: 'CABA',
        fullName: 'Ciudad Autónoma de Buenos Aires',
        poderJudicial: { name: 'Poder Judicial CABA', url: 'https://www.jusbaires.gob.ar' },
        expedientes: { name: 'Consulta de Expedientes (EJE)', url: 'https://eje.jus.gob.ar' },
        colegio: { name: 'Colegio Público de Abogados CABA', url: 'https://www.cpacf.org.ar' },
        mev: { name: 'Mesa de Entradas Virtual (MEV)', url: 'https://mev.jus.gob.ar' },
        extras: [
            { name: 'Centro de Mediación', url: 'https://www.jus.gob.ar/mediacion' },
        ],
    },
    {
        province: 'Buenos Aires',
        fullName: 'Provincia de Buenos Aires',
        poderJudicial: { name: 'SCBA - Suprema Corte', url: 'https://www.scba.gov.ar' },
        expedientes: { name: 'MEV (Augusta)', url: 'https://mev.scba.gov.ar' },
        colegio: { name: 'Colegio de Abogados (COLPROBA)', url: 'https://www.colproba.org.ar' },
        mev: { name: 'Notificaciones y Presentaciones Electrónicas', url: 'https://notificaciones.scba.gov.ar' },
        extras: [
            { name: 'Receptoría General de Expedientes', url: 'https://www.scba.gov.ar/informacion/rge.asp' },
            { name: 'Junta Electoral PBA', url: 'https://www.juntaelectoral.gba.gov.ar' },
        ],
    },
    {
        province: 'Catamarca',
        fullName: 'Provincia de Catamarca',
        poderJudicial: { name: 'Poder Judicial Catamarca', url: 'https://www.juscatamarca.gob.ar' },
        expedientes: { name: 'Consulta de Expedientes', url: 'https://www.juscatamarca.gob.ar/consultaexpedientes' },
        colegio: { name: 'Colegio de Abogados de Catamarca', url: 'https://www.colegioabogadoscatamarca.org.ar' },
        mev: null,
        extras: [],
    },
    {
        province: 'Chaco',
        fullName: 'Provincia del Chaco',
        poderJudicial: { name: 'Poder Judicial del Chaco', url: 'https://www.justiciachaco.gov.ar' },
        expedientes: { name: 'Consulta de Causas', url: 'https://www.justiciachaco.gov.ar/consultadecausas' },
        colegio: { name: 'Colegio de Abogados del Chaco', url: 'https://www.colegioabogadoschaco.org.ar' },
        mev: null,
        extras: [],
    },
    {
        province: 'Chubut',
        fullName: 'Provincia del Chubut',
        poderJudicial: { name: 'Poder Judicial del Chubut', url: 'https://www.juschubut.gov.ar' },
        expedientes: { name: 'Sistema de Gestión', url: 'https://www.juschubut.gov.ar' },
        colegio: { name: 'Colegio de Abogados del Chubut', url: 'https://www.colegioabogadoschubut.org.ar' },
        mev: null,
        extras: [],
    },
    {
        province: 'Córdoba',
        fullName: 'Provincia de Córdoba',
        poderJudicial: { name: 'Poder Judicial de Córdoba', url: 'https://www.justiciacordoba.gob.ar' },
        expedientes: { name: 'SAC (Sistema de Administración de Causas)', url: 'https://www.justiciacordoba.gob.ar/JusticiaCordoba/Inicio/indexDetalle.aspx?codNovedad=17862' },
        colegio: { name: 'Colegio de Abogados de Córdoba', url: 'https://www.abogados-cba.org.ar' },
        mev: { name: 'Actuaciones Electrónicas', url: 'https://www.justiciacordoba.gob.ar' },
        extras: [
            { name: 'TSJ Córdoba', url: 'https://www.justiciacordoba.gob.ar' },
        ],
    },
    {
        province: 'Corrientes',
        fullName: 'Provincia de Corrientes',
        poderJudicial: { name: 'Poder Judicial de Corrientes', url: 'https://www.juscorrientes.gov.ar' },
        expedientes: { name: 'Consulta de Expedientes', url: 'https://www.juscorrientes.gov.ar' },
        colegio: { name: 'Colegio de Abogados de Corrientes', url: 'https://www.colegioabogadoscorrientes.org.ar' },
        mev: null,
        extras: [],
    },
    {
        province: 'Entre Ríos',
        fullName: 'Provincia de Entre Ríos',
        poderJudicial: { name: 'Poder Judicial de Entre Ríos', url: 'https://www.jusentrerios.gov.ar' },
        expedientes: { name: 'Sistema de Gestión (Augusto)', url: 'https://www.jusentrerios.gov.ar' },
        colegio: { name: 'Colegio de Abogados de Entre Ríos', url: 'https://www.colegioabogadoser.org.ar' },
        mev: { name: 'Notificaciones Electrónicas', url: 'https://www.jusentrerios.gov.ar' },
        extras: [
            { name: 'STJ Entre Ríos', url: 'https://www.jusentrerios.gov.ar' },
        ],
    },
    {
        province: 'Formosa',
        fullName: 'Provincia de Formosa',
        poderJudicial: { name: 'Poder Judicial de Formosa', url: 'https://www.jusformosa.gob.ar' },
        expedientes: { name: 'Consulta de Expedientes', url: 'https://www.jusformosa.gob.ar' },
        colegio: { name: 'Colegio de Abogados de Formosa', url: 'https://www.colegioabogadosformosa.org.ar' },
        mev: null,
        extras: [],
    },
    {
        province: 'Jujuy',
        fullName: 'Provincia de Jujuy',
        poderJudicial: { name: 'Poder Judicial de Jujuy', url: 'https://www.justiciajujuy.gov.ar' },
        expedientes: { name: 'Consulta de Expedientes', url: 'https://www.justiciajujuy.gov.ar' },
        colegio: { name: 'Colegio de Abogados de Jujuy', url: 'https://www.colegiodeabogadosjujuy.org.ar' },
        mev: null,
        extras: [],
    },
    {
        province: 'La Pampa',
        fullName: 'Provincia de La Pampa',
        poderJudicial: { name: 'Poder Judicial de La Pampa', url: 'https://www.juslapampa.gob.ar' },
        expedientes: { name: 'Consulta de Expedientes', url: 'https://www.juslapampa.gob.ar' },
        colegio: { name: 'Colegio de Abogados de La Pampa', url: 'https://www.colegioabogadoslapampa.org.ar' },
        mev: null,
        extras: [],
    },
    {
        province: 'La Rioja',
        fullName: 'Provincia de La Rioja',
        poderJudicial: { name: 'Poder Judicial de La Rioja', url: 'https://www.justicialaroja.gob.ar' },
        expedientes: { name: 'Consulta de Causas', url: 'https://www.justicialaroja.gob.ar' },
        colegio: { name: 'Colegio de Abogados de La Rioja', url: 'https://www.colegioabogadoslarioja.org.ar' },
        mev: null,
        extras: [],
    },
    {
        province: 'Mendoza',
        fullName: 'Provincia de Mendoza',
        poderJudicial: { name: 'Poder Judicial de Mendoza', url: 'https://www.jus.mendoza.gov.ar' },
        expedientes: { name: 'GDE - Gestión Digital de Expedientes', url: 'https://www2.jus.mendoza.gov.ar/listas/proveidos/consulta.php' },
        colegio: { name: 'Colegio de Abogados de Mendoza', url: 'https://www.colegioabogadosmza.org.ar' },
        mev: { name: 'Notificaciones Electrónicas', url: 'https://www2.jus.mendoza.gov.ar' },
        extras: [],
    },
    {
        province: 'Misiones',
        fullName: 'Provincia de Misiones',
        poderJudicial: { name: 'Poder Judicial de Misiones', url: 'https://www.jusmisiones.gov.ar' },
        expedientes: { name: 'Consulta de Expedientes', url: 'https://www.jusmisiones.gov.ar' },
        colegio: { name: 'Colegio de Abogados de Misiones', url: 'https://www.colegioabogadosmisiones.org.ar' },
        mev: null,
        extras: [],
    },
    {
        province: 'Neuquén',
        fullName: 'Provincia de Neuquén',
        poderJudicial: { name: 'Poder Judicial de Neuquén', url: 'https://www.jusneuquen.gov.ar' },
        expedientes: { name: 'Consulta de Causas', url: 'https://www.jusneuquen.gov.ar' },
        colegio: { name: 'Colegio de Abogados de Neuquén', url: 'https://www.colegioabogadosneuquen.org.ar' },
        mev: null,
        extras: [],
    },
    {
        province: 'Río Negro',
        fullName: 'Provincia de Río Negro',
        poderJudicial: { name: 'Poder Judicial de Río Negro', url: 'https://www.jusrionegro.gov.ar' },
        expedientes: { name: 'Consulta de Expedientes', url: 'https://www.jusrionegro.gov.ar' },
        colegio: { name: 'Colegio de Abogados de Río Negro', url: 'https://www.colegioabogadosrionegro.org.ar' },
        mev: null,
        extras: [],
    },
    {
        province: 'Salta',
        fullName: 'Provincia de Salta',
        poderJudicial: { name: 'Poder Judicial de Salta', url: 'https://www.justiciasalta.gov.ar' },
        expedientes: { name: 'Consulta de Expedientes', url: 'https://www.justiciasalta.gov.ar/consultaexpedientes' },
        colegio: { name: 'Colegio de Abogados de Salta', url: 'https://www.colegioabogadossalta.org.ar' },
        mev: null,
        extras: [],
    },
    {
        province: 'San Juan',
        fullName: 'Provincia de San Juan',
        poderJudicial: { name: 'Poder Judicial de San Juan', url: 'https://www.jussanjuan.gov.ar' },
        expedientes: { name: 'Consulta de Causas', url: 'https://www.jussanjuan.gov.ar' },
        colegio: { name: 'Colegio de Abogados de San Juan', url: 'https://www.colegioabogadossanjuan.org.ar' },
        mev: null,
        extras: [],
    },
    {
        province: 'San Luis',
        fullName: 'Provincia de San Luis',
        poderJudicial: { name: 'Poder Judicial de San Luis', url: 'https://www.justicia.sanluis.gov.ar' },
        expedientes: { name: 'Consulta de Expedientes', url: 'https://www.justicia.sanluis.gov.ar' },
        colegio: { name: 'Colegio de Abogados de San Luis', url: 'https://www.colegioabogadossanluis.org.ar' },
        mev: null,
        extras: [],
    },
    {
        province: 'Santa Cruz',
        fullName: 'Provincia de Santa Cruz',
        poderJudicial: { name: 'Poder Judicial de Santa Cruz', url: 'https://www.jussantacruz.gob.ar' },
        expedientes: { name: 'Consulta de Expedientes', url: 'https://www.jussantacruz.gob.ar' },
        colegio: { name: 'Colegio de Abogados de Santa Cruz', url: 'https://www.colegioabogadossantacruz.org.ar' },
        mev: null,
        extras: [],
    },
    {
        province: 'Santa Fe',
        fullName: 'Provincia de Santa Fe',
        poderJudicial: { name: 'Poder Judicial de Santa Fe', url: 'https://www.justiciasantafe.gov.ar' },
        expedientes: { name: 'MOE - Módulo de Operaciones Electrónicas', url: 'https://www.justiciasantafe.gov.ar' },
        colegio: { name: 'Colegio de Abogados de Santa Fe', url: 'https://www.colegioabogadossantafe.org.ar' },
        mev: { name: 'Notificaciones Electrónicas', url: 'https://www.justiciasantafe.gov.ar' },
        extras: [],
    },
    {
        province: 'Santiago del Estero',
        fullName: 'Provincia de Santiago del Estero',
        poderJudicial: { name: 'Poder Judicial de Santiago del Estero', url: 'https://www.jussde.gov.ar' },
        expedientes: { name: 'Consulta de Expedientes', url: 'https://www.jussde.gov.ar' },
        colegio: { name: 'Colegio de Abogados de Santiago del Estero', url: 'https://www.colegioabogadossde.org.ar' },
        mev: null,
        extras: [],
    },
    {
        province: 'Tierra del Fuego',
        fullName: 'Provincia de Tierra del Fuego',
        poderJudicial: { name: 'Poder Judicial de Tierra del Fuego', url: 'https://www.justierradelfuego.gov.ar' },
        expedientes: { name: 'Consulta de Causas', url: 'https://www.justierradelfuego.gov.ar' },
        colegio: { name: 'Colegio de Abogados de Tierra del Fuego', url: 'https://www.colegioabogadostdf.org.ar' },
        mev: null,
        extras: [],
    },
    {
        province: 'Tucumán',
        fullName: 'Provincia de Tucumán',
        poderJudicial: { name: 'Poder Judicial de Tucumán', url: 'https://www.justucuman.gov.ar' },
        expedientes: { name: 'SAE - Sistema de Administración de Expedientes', url: 'https://www.justucuman.gov.ar' },
        colegio: { name: 'Colegio de Abogados de Tucumán', url: 'https://www.colegioabogadostucuman.org.ar' },
        mev: null,
        extras: [],
    },
    {
        province: 'Federal',
        fullName: 'Justicia Nacional y Federal',
        poderJudicial: { name: 'Poder Judicial de la Nación', url: 'https://www.pjn.gov.ar' },
        expedientes: { name: 'Consulta de Expedientes (CIJ)', url: 'https://www.cij.gov.ar' },
        colegio: { name: 'FACA - Federación Argentina de Colegios de Abogados', url: 'https://www.faca.org.ar' },
        mev: { name: 'EJE - Expediente Judicial Electrónico', url: 'https://eje.jus.gob.ar' },
        extras: [
            { name: 'SAIJ - Sistema Argentino de Información Jurídica', url: 'https://www.saij.gob.ar' },
            { name: 'InfoLEG - Información Legislativa', url: 'https://www.infoleg.gob.ar' },
            { name: 'Boletín Oficial', url: 'https://www.boletinoficial.gob.ar' },
        ],
    },
];

export const survivalGuides = [
    {
        id: 'presentacion-electronica',
        title: 'Presentación Electrónica Federal',
        category: 'Trámites Digitales',
        icon: 'FileText',
        difficulty: 'Básico',
        steps: [
            'Obtener el certificado digital (firma electrónica) del Colegio de Abogados correspondiente.',
            'Registrarse en el sistema EJE (eje.jus.gob.ar) con CUIT/CUIL y certificado.',
            'Crear la presentación en formato PDF/A (no más de 10MB por archivo).',
            'Ingresar al expediente, seleccionar "Nueva Presentación" y adjuntar el escrito firmado digitalmente.',
            'Verificar que el cargo electrónico se haya generado correctamente (descargar comprobante).',
        ],
        tips: [
            'Los escritos deben ser en PDF/A — usar "Guardar como PDF/A" en Word o LibreOffice.',
            'Si el archivo supera 10MB, dividirlo en partes y presentar como "Documentación adjunta".',
            'El horario de presentación es 24/7, pero el cargo se computa en día hábil siguiente si se presenta fuera de horario.',
        ],
    },
    {
        id: 'oficios-ley-22172',
        title: 'Oficios Ley 22.172 (Interjurisdiccional)',
        category: 'Interjurisdiccional',
        icon: 'Globe',
        difficulty: 'Intermedio',
        steps: [
            'Solicitar al juez de origen la confección del oficio Ley 22.172.',
            'El oficio debe contener: carátula, objeto, juez exhortante, juez exhortado, y transcripción de la resolución.',
            'Obtener la legalización del oficio por el Superior Tribunal de la jurisdicción de origen.',
            'Presentar el oficio ante el juzgado destinatario en la jurisdicción de destino.',
            'Acreditar el diligenciamiento mediante cédula o acta de notificación local.',
        ],
        tips: [
            'Algunas jurisdicciones aceptan oficios electrónicos — verificar con el tribunal destino.',
            'El corresponsal en destino puede diligenciar el oficio sin necesidad de poder especial.',
            'Tener en cuenta los feriados locales de la jurisdicción destino al calcular plazos.',
        ],
    },
    {
        id: 'mediacion-obligatoria',
        title: 'Mediación Prejudicial Obligatoria (CABA)',
        category: 'Mediación',
        icon: 'Users',
        difficulty: 'Básico',
        steps: [
            'Registrarse como requirente en el sistema MEPRE (mediaciones.gob.ar).',
            'Sortear mediador — el sistema asigna automáticamente.',
            'Notificar a la parte requerida con 3 días hábiles de anticipación.',
            'Asistir a la audiencia de mediación (presencial o virtual según acuerdo).',
            'Obtener el acta de cierre: con acuerdo (título ejecutivo) o sin acuerdo (habilita vía judicial).',
        ],
        tips: [
            'La mediación es obligatoria en casi todos los juicios civiles y comerciales en CABA.',
            'Si el requerido no se presenta, solicitar segunda audiencia. Si no asiste nuevamente, se cierra sin acuerdo.',
            'Las excepciones incluyen: amparos, habeas corpus, medidas cautelares, ejecuciones, desalojos.',
        ],
    },
    {
        id: 'inscripcion-corresponsal',
        title: 'Registrarse como Corresponsal en Judic-IA',
        category: 'Plataforma',
        icon: 'Shield',
        difficulty: 'Básico',
        steps: [
            'Ir a Configuración > Perfil Profesional en tu dashboard.',
            'Completar todos los datos obligatorios: matrícula, jurisdicción, especialidades.',
            'Activar la opción "Disponible como Corresponsal" e indicar tu zona de cobertura.',
            'Esperar la verificación de matrícula por el equipo de Judic-IA (24-48hs).',
            'Una vez verificado, tu perfil aparecerá en el Hub Federal para colegas de otras jurisdicciones.',
        ],
        tips: [
            'A mayor detalle en tu perfil (biografía, especialidades, zona), más solicitudes recibirás.',
            'Podés desactivar temporalmente tu disponibilidad sin perder la verificación.',
            'Los chats entre corresponsales son privados y no pasan por el sistema de consultas.',
        ],
    },
];
